### PR TITLE
fix yaml syntax in yaml tutorial

### LINKED ISSUE #347: Broken YAML SYNTAX example
Here is example: https://github.com/getgrav/grav-learn/blob/develop/pages/08.advanced/11.yaml/docs.md#mappings

```yml
animal: pets
- Cat
- Dog
- Goldfish
```

but it doesn't work in pyyaml and http://www.yamllint.com/ with error:
```
yaml.parser.ParserError: while parsing a block mapping
  in "test.yml", line 1, column 1
expected <block end>, but found '-'
  in "test.yml", line 2, column 1
```

I could fix it, but I'm not sure I'm clear with goal of example..

### PR DESCRIPTION
**Pull request by Frodox**
resolve #347

### CODE REVIEW

**Comment by rhukster** [comment]
Actually we use `.yaml` exclusively. .yml will cause issues

**Review by rhukster — CHANGES_REQUESTED** [review]
.yml is not valid inside of grav only .yaml

**Comment by Frodox** [comment]
@rhukster ok.
Interesting why, because python parser is universal O.o :) Then you need to change `.travis.yml` and `codeception.yml` to `.yaml` to prevent newbies (as me) confusing.

**Comment by rhukster** [comment]
Those are 3rd party systems and they actually require .yml. We however prefer .yaml

**Comment by Frodox** [comment]
@rhukster updated!

**Pull request merged**
