### PR TITLE
Correct inconsistencies in directory naming and request update to pages....

### PR DESCRIPTION
**Pull request by tgshannon**
...jpg image

I noticed an inconsistency in the Directory Relative section, and while trying to figure out I also noticed that the pages.jpg file is either wrong or I'm confused. So, I'm assuming that the pages.jpg file is incorrect and that the directories under pages should be: 01.blue and 02.green and not 01.blue and 01.green.

### CODE REVIEW

**Comment by rhukster** [comment]
Thanks for these.  I updated the linking bit a while ago and didn't reflect that in the docs.

**Comment by tgshannon** [comment]
It still looks like the pages.jpg image file near the top of the page needs to be replaced. I wasn't able to modify this in the pull request. It shows the page files as 01.blue and 01.green. I think they should be 01.blue and 02.green -  Yes?

**Comment by rhukster** [comment]
Ryan do you have this folder structure still? I think you created the image? If not i'll recreate it and fix the image.

**Comment by RyanMPierson** [comment]
I believe I can replicate it.

**Comment by RyanMPierson** [comment]
The image has been fixed in develop branch.

**Pull request merged**
