### PR TITLE
pages/02.content/01.content-pages/docs.md

### PR DESCRIPTION
**Pull request by mychapra**

### CODE REVIEW

**Comment by mychapra** [comment]
pages/02.content/01.content-pages/docs.md

**Comment by mychapra** [comment]
[mychapra--master.zip](https://github.com/getgrav/grav-learn/files/3465136/mychapra--master.zip)

**Review by mychapra — COMMENTED** [review]
[grav-admin-v1.6.11.zip](https://github.com/getgrav/grav-learn/files/3465139/grav-admin-v1.6.11.zip)
[mychapra--master.zip](https://github.com/getgrav/grav-learn/files/3465141/mychapra--master.zip)

**Comment by mychapra** [comment]
+[/prism]

**Comment by mychapra** [comment]
-[/prism]

**Comment by rhukster** [comment]
no changes...

**Pull request closed without merging**
