### PR TITLE
windows cli stuff

### PR DESCRIPTION
**Pull request by robwent**

### CODE REVIEW

**Comment by rhukster** [comment]
Same info on this one?

**Comment by rhukster** [comment]
Thanks!

**Comment by robwent** [comment]
no problem. I learnt that I should be using bash rather than cmd :)

**Comment by rhukster** [comment]
I don't know how you guys do it :) Mac's are just so much easier...

**Comment by robwent** [comment]
ahhh, I'm not going to get drawn into that one :)

**Pull request merged**
