### PR TITLE
Add page about installing a plugin:

### PR DESCRIPTION
**Pull request by arkhi**
This would allow plugins to point to the page to keep their README shorter and more up to date with Grav evolution.

The plugins could link to specific version of the page if needed, as [04.grav-lifecycle/docs.16.md](https://github.com/getgrav/grav-learn/blob/e3552b15c5845b74dedc9233d887db45225e626c/pages/04.plugins/04.grav-lifecycle/docs.16.md) does.

Just a proposal to limit everybody’s maintenance. I think the trade‑off of not being able to just copy/paste one line of code is worth it. :)

### CODE REVIEW

**Comment by rhukster** [comment]
Currently has conflicts....

**Comment by arkhi** [comment]
Yes; this is a bit tricky as I think the plugin installation steps would make more sense in the first steps, but moving them before other pages causes the conflicts because the directories need to be renamed.

Do you have any suggestion about how to handle this dilemma best, or should the Installation page appear last as to not create those conflicts?

**Comment by arkhi** [comment]
Nevermind. :p

**Comment by arkhi** [comment]
Merge conflicts were fixed after pulling from getgrav; I don’t know what happened exactly as I thought I started from a clean version of the repository.

Thank you for your comment; all’s green now.

**Comment by mahagr** [comment]
Conflicts were due to the renaming of the files which were modified.

**Pull request merged**
