### PR TITLE
Updating docs to have wget download to specific file (Fixes #597)

### LINKED ISSUE #597: Ubuntu documentation wget download zip file to wrong location
The `wget` command in the Ubuntu documentation downloads the file to `latest` instead of to `grav-v{{ grav_version }}.zip`.

### PR DESCRIPTION
**Pull request by pcon**

### CODE REVIEW

**Comment by rhukster** [comment]
This requires you to manually enter the latest version though. Grabbing `/latest` always gets the latest version.. should just add a command to rename the file after if that's a problem?

**Comment by pcon** [comment]
@rhukster I was just naming it to what the `unzip` command was trying to unzip.  I can easily modify this to be `grav-latest.zip` and then unzip that file.  Thoughts?

**Comment by rhukster** [comment]
That would be better i think.

**Comment by rhukster** [comment]
tannks

**Pull request merged**
