### PR TITLE
windows cli stuff

### PR DESCRIPTION
**Pull request by robwent**

### CODE REVIEW

**Comment by rhukster** [comment]
Is Gitbash included in the Git .exe file `Git-1.9.4-preview20140929.exe` ? It's not very clear on the Git website.

**Comment by robwent** [comment]
yeah, the installer includes git, gitbash and integrates git into shell.

Maybe this might be a better link? http://msysgit.github.io/ the download link is the same

**Comment by rhukster** [comment]
Yes, I think so, and perhaps in the text, you can mention what it includes?

**Comment by rhukster** [comment]
Yah, mo better. thanks!

**Pull request merged**
