### PR TITLE
[WIP] Proof-Reading

### PR DESCRIPTION
**Pull request by grav-it**
Collection of commits that correct all found mistakes. Partly opinionated.

Discussion welcome.

**Tasks:**

- [x] Prepend commit titles with edited file name for better progress visibility.

### CODE REVIEW

**Review by OleVik — APPROVED** [review]
All sensible improvements for consistency and clarity.

**Comment by grav-it** [comment]
Thanks @OleVik. Making good progress.

Is there a reason why some pages do not have a TOC?

**Comment by rhukster** [comment]
> Thanks @OleVik. Making good progress.
> 
> Is there a reason why some pages do not have a TOC?

TOC have been added only to longer pages that really benefit from it.

**Comment by grav-it** [comment]
That doesn't seem right.

[Theme Tutorial: Step 5 - Breaking it Down](https://learn.getgrav.org/16/themes/theme-tutorial#step-5-breaking-it-down)

First list item. There is no `theme_config` variable set in the `base.html.twig` template.

Missing in the [grav-plugin-devtools](https://github.com/getgrav/grav-plugin-devtools/blob/develop/components/theme/pure-blank/templates/partials/base.html.twig) repo, or outdated docs?

Edit: List item 5. Included file `metadata.html.twig` is missing in `partials` folder.
Edit: List items 9 and 11. `assets.css` and `assets.js` are now wrapped inside `block assets deferred`.

**Comment by rhukster** [comment]
Thanks, was beefy!

**Pull request merged**
