### PR TITLE
Add docs for responsive images using sizes

### PR DESCRIPTION
**Pull request by attiks**
First try for the docs of https://github.com/getgrav/grav/pull/325

PS: I can not see the tabs, but I guess they will work
PSS: No idea how to make this work with markdown: `Retina Image 100vw, 50vw')` fails to render

### CODE REVIEW

**Comment by rhukster** [comment]
Thanks I will fix them up.

**Comment by rhukster** [comment]
Regarding markdown:

```
{{ page.media['sample-image.jpg'].derivatives(320, 1440, 100).sizes('(max-width:26em) 100vw, 50vw').html() }}
```

Should be:

```
![](sample-image.jpg?derivatives=320,1440,100&sizes=%28max-width%3A26em%29+100vw%2C+50vw)
```

Where the sizes is **urlencoded**.  However i'm not 100% sure that our current code would work with that, so it would need to be tested and debugged/fixed.

**Comment by attiks** [comment]
I tried it, but the output is messed up, although sizes is working 

```
<img sizes="%28max-width%3A26em%29+100vw%2C+50vw" ... >
```

Do we need a decode inside the sizes method?

**Comment by rhukster** [comment]
Yes, it needs to be decoded in the ParsedownGravTrait.. i think here: 

```
                    // loop through actions for the image and call them
                    foreach ($actions as $action) {
                        $medium = call_user_func_array(array($medium, $action['method']), explode(',', $action['params']));
                    }
```

**Comment by rhukster** [comment]
line 169, change it to this:

```
    $medium = call_user_func_array(array($medium, $action['method']), explode(',', urldecode($action['params'])));

```

**Comment by attiks** [comment]
Works, thanks

**Comment by rhukster** [comment]
will be in the next release.

**Pull request merged**
