### PR TITLE
Initial 'plugin recipes' submission for discussion

### PR DESCRIPTION
**Pull request by Perlkonig**
After a discussion with @rhukster about wikis, I thought I'd gather some thoughts together and make an initial submission for discussion.
- I don't expect this PR to be accepted as is. I appreciate it is different in style from the rest of the documentation. This is a starting off point.
- This represents the sorts of questions I had as I started this plugin coding spree and struggled to find answers to in the core documentation. My desire is to make things easier for the next person to find what they need. Sure there's lots to glean from the source code, but there are a _lot_ of plugins to wade through, and I'm not a PHP native, so I struggled sometimes to differentiate between core PHP functions and Grav-specific ones.
- There may well be better, more specific places for some of this documentation. Since they're all plugin related, I thought the cookbook made the most sense.
- I recognize my own plugins get mentioned a lot. That's only because they're the ones I'm most familiar with. I tried hard to highlight other plugins where possible. There's no self-promotion intended.

I warmly welcome any and all feedback. Thanks for your time.

### CODE REVIEW

**Review by rhukster — APPROVED** [review]
Looks good!

**Comment by rhukster** [comment]
I'm more inclined to accept it as-is and work on it 'live' so to speak.  A living document is not necessarily a bad thing :)

**Comment by rhukster** [comment]
@FrugalGeek thoughts on this plus layout?

**Review by flaviocopes — APPROVED** [review]

**Comment by flaviocopes** [comment]
@FrugalGeek think we can merge it?

**Pull request merged**
