### PR TITLE
Thought this might be of interest to others for use in any theme.

### PR DESCRIPTION
**Pull request by paulhibbitts**

### CODE REVIEW

**Comment by flaviocopes** [comment]
Cool @paulhibbitts, but I think this can be simplified even more: Grav by default in all pages has a `body_classes` header property, which you can set in the page's Advanced tab.

The theme must implement it, like Antimatter for example: https://github.com/getgrav/grav-theme-antimatter/blob/develop/templates/partials/base.html.twig#L41

(also listed in https://learn.getgrav.org/themes/theme-tutorial#step-4-base-template and https://learn.getgrav.org/content/modular#setting-up-the-primary-page, but worth adding to the recipes as well. Do you think this can be reworded to use that header property?

**Comment by paulhibbitts** [comment]
A-ok, how about something that includes both methods, for example like this:


How can you dynamically style one or more posts/pages?

You can style different posts/pages in your Grav site by two methods:
1.  If you are using the AntiMatter theme, you can use the existing `body_classes` header property to set your custom CSS class for that page
2.  If you are using a theme not based on AntiMatter, you can customize a Theme's Twig file to apply a CSS class passed as a variable in a page's header property

For example, in your theme's `base.html.twig` file or a more specific template such as `page.html.twig` file you could add a class to the display of page content, such as:

```
<div class="{{ page.header.cssclass }}">
...
</div>
```

Then, for each page you wish to have a unique style, you would add the following header property (assuming you have defined a CSS class for `featurepost`):

```
cssclass: featurepost
```

**Comment by OleVik** [comment]
Since `body_classes` is global, it is applicable in any theme that utilises it, I think the recommendation should be that the theme implement `<body class="{{ page.header.body_classes }}">` in `base.html.twig` (or their equivalent). Further, since it is page-specific theme-authors can choose to utilise the classes on any element they see fit - be it `<body>` or `<x>`.

That is to say, the recipe advises to use ` class="{{ page.header.body_classes }}"` in a global template (like `base.html.twig`) or regional template (like `post.html.twig`) to use page-specific styles - which are added in the theme's CSS. This takes advantage of Grav's global `body_classes` (always present in page-blueprints) and promotes the minimal implementation of the feature, as it simply adds in a new level of specificity for CSS-declarations.

**Comment by OleVik** [comment]
Just to clarify so I'm not mistaken: Is `body_classes` global to Grav or added specifically by Antimatter? If it is the case that `body_classes` is global, that is, available in any theme by default, I would go with 

```
Dynamically style one or more pages

You can dynamically style different pages/posts in your Grav site (independent of template file assignment) by customizing a Theme's Twig file to apply a CSS class passed as a variable in a page's FrontMatter. You can style different posts/pages in your Grav site by using the existing body_classes header property to set your custom CSS class for that page.

For example, in your theme's base.html.twig file or a more specific template such as page.html.twig file you could add a class to the display of page content, such as:

<div class="{{ page.header.body_classes }}">
...
</div>
```

But if it is not globally available, I would still recommend it as a standard to be used:

```
Dynamically style one or more pages

You can dynamically style different pages/posts in your Grav site (independent of template file assignment) by customizing a Theme's Twig file to apply a CSS class passed as a variable in a page's FrontMatter.

You can style different posts/pages in your Grav site by two methods:

1. If you are using the AntiMatter theme, you can use the existing body_classes header property to set your custom CSS class for that page.
2. If you are using a theme not based on AntiMatter, you can customize a Theme's Twig file to apply a CSS class passed as a variable in a page's header property

For example, in your theme's base.html.twig file or a more specific template such as page.html.twig file you could add a class to the display of page content, such as:

<div class="{{ page.header.body_classes }}">
...
</div>

Then, for each page you wish to have a unique style, you would add the following header property (assuming you have defined a CSS class for featurepost):

body_classes: featurepost
```

`body_classes` is a sensible standard to implement in themes, and the nomenclature is the same so people can swap themes but still apply the custom classes to the same pages - which is handy when a specific page has a specific design, apart from the overall theme, and thus requires less adaptation with theme-inheritance or custom assets.

And for the last tidbit, replace "This recipe was originally described by OleVik" with "This is how the Antimatter-theme applies page-specific classes, and its a good standard to follow." I may have suggested the method recently, but I originally lifted it off Antimatter as an efficient way to tweak pages CSS.

**Comment by paulhibbitts** [comment]
Thanks for the additional comments @olevik, I've revised my PR based on your input and tweaked a few little things at the same time.

**Review by OleVik — CHANGES_REQUESTED** [review]
Think a few ticks may have gotten lost in translation: Around `body_classes` and `featurepost`.

**Comment by flaviocopes** [comment]
Thanks @paulhibbitts :)

**Pull request merged**
