### PR TITLE
Add an admin special form field

### PR DESCRIPTION
**Pull request by paulmassen**
The blueprint option 'pagemedia' wasn't in this list whereas it works

### CODE REVIEW

**Comment by rhukster** [comment]
This is a special field that really only works when working with pages.  That's probably why it wasn't listed initially.  Also the first letter should be capitalized.

**Comment by flaviocopes** [comment]
Right, closing this as I changed the blueprints fields reference, and it's no longer using this page structure, but still that field is missing, nice to be listed as well to build custom pages. Marking to add.

**Comment by paulmassen** [comment]
hmm in my admin blueprints, it doesn't work when any of these references are capitalized:
PageMediaSelect doesn't work whereas pagemediaselect works

**Comment by flaviocopes** [comment]
Yep it needs to be lowercase, it's probably capitalized as a "title", but it's used lowercase, e.g. http://learn.getgrav.org/forms/blueprints/fields-available#the-pagemediaselect-field

**Comment by flaviocopes** [comment]
Will change for clarity

**Pull request closed without merging**
