### PR TITLE
Chapter about Nginx

### PR DESCRIPTION
**Pull request by simonhaenisch**
Finally I finished the chapter about using Grav with Nginx. See issue getgrav/grav#247

### CODE REVIEW

**Comment by simonhaenisch** [comment]
I just found a few things I want to improve after I tested my config with Google PageSpeed Insights, so this can wait until I make a few commits.

**Comment by simonhaenisch** [comment]
I am done with my edits so far.

There is one thing I head problems with: setting "Expires" headers for static content, i.e. js, css and images. I tried to use some [rules from h5bp](https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/location/expires.conf), but the Media part of it results in "404: Not found" errors, because image urls get rewritten by Grav (e.g. `user/pages/01.home/image.jpg` becomes `home/image.jpg`).

I saw in the `user/config/system.yaml` file that you can specify an expiration time to be added as header, so setting the headers via Nginx is probably not necessary?

**Comment by rhukster** [comment]
Will review this shortly. Thanks!

**Comment by rhukster** [comment]
I have some minor edits, but i'll just make them to the merged version. Thanks again!

**Comment by simonhaenisch** [comment]
Ok sure, edit as much as you want ;) You're welcome!

**Pull request merged**
